# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Elapsed < Formula
  desc "Simple utility which adds elapsed time markers on every input line"
  homepage "https://github.com/jittering/elapsed"
  version "0.10"

  on_macos do
    on_intel do
      url "https://github.com/jittering/elapsed/releases/download/v0.10/elapsed_0.10_darwin_amd64"
      sha256 "0e4aa411891a9ab3b5315660ae5fd76398e99494936c64767ff14e9edc8290cb"

      def install
        bin.install "elapsed_0.10_darwin_amd64" => "elapsed"
      end
    end
    on_arm do
      url "https://github.com/jittering/elapsed/releases/download/v0.10/elapsed_0.10_darwin_arm64"
      sha256 "6dfc297e9eb93f8869c36b53b96682a5a6eccb4cc95c84cefea2f7df01cf39d3"

      def install
        bin.install "elapsed_0.10_darwin_arm64" => "elapsed"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jittering/elapsed/releases/download/v0.10/elapsed_0.10_linux_amd64"
        sha256 "ceef33033d3596d88508be5841c9da11d626dee78bfae89dc232086eb1ac1fda"

        def install
          bin.install "elapsed_0.10_linux_amd64" => "elapsed"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/jittering/elapsed/releases/download/v0.10/elapsed_0.10_linux_armv6"
        sha256 "b9884356e170a5cf170fadc060b0cee6c535741bbe56d17b05fddd7adf1ad410"

        def install
          bin.install "elapsed_0.10_linux_armv6" => "elapsed"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jittering/elapsed/releases/download/v0.10/elapsed_0.10_linux_arm64"
        sha256 "7f6cf11fdf3dfbaa799f627cc066fb4129c85f2732d6e17f8aaaa92346b8a676"

        def install
          bin.install "elapsed_0.10_linux_arm64" => "elapsed"
        end
      end
    end
  end
end
