# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Elapsed < Formula
  desc "Simple utility which adds elapsed time markers on every input line"
  homepage "https://github.com/jittering/elapsed"
  version "0.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jittering/elapsed/releases/download/v0.9/elapsed_0.9_Darwin_x86_64"
      sha256 "8c3a2f5306b2c86ad1ac0b94610acfde5d9f91ab67d8ce89929a84864e4a11d4"

      def install
        bin.install "elapsed_0.9_Darwin_x86_64" => "elapsed"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jittering/elapsed/releases/download/v0.9/elapsed_0.9_Darwin_arm64"
      sha256 "f36b79aded4f4a877860646fba5128a12df9a2493e6044d3f974a4808df8f4d4"

      def install
        bin.install "elapsed_0.9_Darwin_arm64" => "elapsed"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jittering/elapsed/releases/download/v0.9/elapsed_0.9_Linux_x86_64"
      sha256 "7fb60062a8c39b9d2f961818c75f6b9bc52a40c744a9cfa1e6f77bd4cf6e0ca4"

      def install
        bin.install "elapsed_0.9_Linux_x86_64" => "elapsed"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jittering/elapsed/releases/download/v0.9/elapsed_0.9_Linux_arm64"
      sha256 "8986a881abb0996b6733933301ee214abc8f2f7283e5fc6ad54c905c28d84937"

      def install
        bin.install "elapsed_0.9_Linux_arm64" => "elapsed"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/jittering/elapsed/releases/download/v0.9/elapsed_0.9_Linux_armv6"
      sha256 "e09f778f7480d85a08433b034664daa8c9cbebaeabcb1ecb2ac75f4f86176016"

      def install
        bin.install "elapsed_0.9_Linux_armv6" => "elapsed"
      end
    end
  end
end
