# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Elapsed < Formula
  desc "A simple utility which adds elapsed time markers on every input line"
  homepage "https://github.com/jittering/elapsed"
  version "0.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jittering/elapsed/releases/download/v0.8/elapsed_0.8_Darwin_x86_64"
      sha256 "42fb4285e957300294942c71289b38c7f95d8f781b1142a46f94352956b5f7d4"

      def install
        bin.install "elapsed_0.8_Darwin_x86_64" => "elapsed"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jittering/elapsed/releases/download/v0.8/elapsed_0.8_Darwin_arm64"
      sha256 "228125eb34679723d5de561d75512e49ca669b59c3785d999e4f0d48da62cacc"

      def install
        bin.install "elapsed_0.8_Darwin_arm64" => "elapsed"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/jittering/elapsed/releases/download/v0.8/elapsed_0.8_Linux_armv6"
      sha256 "fb92cf2a8c402bb5e04fc2e83c6ab1b4d078a903967b2b4ebecea552c2ecc208"

      def install
        bin.install "elapsed_0.8_Linux_armv6" => "elapsed"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jittering/elapsed/releases/download/v0.8/elapsed_0.8_Linux_x86_64"
      sha256 "d62037179797ac83723489ced1e343b1a133c91770446958ba18df7bbe6423c1"

      def install
        bin.install "elapsed_0.8_Linux_x86_64" => "elapsed"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jittering/elapsed/releases/download/v0.8/elapsed_0.8_Linux_arm64"
      sha256 "9ddaec3ed30e20a8c42defa647efe96fd68489a34308655f598dc24d1bc6b903"

      def install
        bin.install "elapsed_0.8_Linux_arm64" => "elapsed"
      end
    end
  end
end
