# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jqplay < Formula
  desc "A local playground for jq"
  homepage "https://github.com/jittering/jqplay"
  version "0.8.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jittering/jqplay/releases/download/v0.8.1/jqplay_0.8.1_Darwin_x86_64"
      sha256 "c04440fb1edba58e7e3750dd4d3e003596b7de0280634f56e34993f6fee610e2"

      def install
        bin.install "jqplay"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jittering/jqplay/releases/download/v0.8.1/jqplay_0.8.1_Linux_x86_64"
      sha256 "8f76e5c31554361a607a59e128e0a992ecdbb840c62e623f51234475564eec88"

      def install
        bin.install "jqplay"
      end
    end
  end
end
