# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jqplay < Formula
  desc "A local playground for jq"
  homepage "https://github.com/jittering/jqplay"
  version "0.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jittering/jqplay/releases/download/v0.8/jqplay_0.8_Darwin_x86_64.tar.gz"
      sha256 "b9ab834a8ef40251423dabc5f7001fe7b5d9c5ef91892ecca529eb3f3c2a1088"

      def install
        bin.install "jqplay"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jittering/jqplay/releases/download/v0.8/jqplay_0.8_Linux_x86_64.tar.gz"
      sha256 "9a6ada13a3a5dd319294cd8f8ea478cfe60352011a65ab6c20cebfd5edb8d765"

      def install
        bin.install "jqplay"
      end
    end
  end
end
