# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JqplayCli < Formula
  desc "Local playground for jq"
  homepage "https://github.com/jittering/jqplay"
  version "0.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jittering/jqplay/releases/download/v0.9/jqplay-cli_0.9_Darwin_x86_64"
      sha256 "4c56c328ff1ba61e0098de13e03e0b20965c2d3c900865aa2ac01e7b44444eb4"

      def install
        bin.install "jqplay-cli_0.9_Darwin_x86_64" => "jqplay-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jittering/jqplay/releases/download/v0.9/jqplay-cli_0.9_Linux_x86_64"
      sha256 "e47c422010752625ee4351126308dfa9ce23c9a40678ec7c8c593c8269332a98"

      def install
        bin.install "jqplay-cli_0.9_Linux_x86_64" => "jqplay-cli"
      end
    end
  end
end
