# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jqplay < Formula
  desc "A local playground for jq"
  homepage "https://github.com/jittering/jqplay"
  version "0.8.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jittering/jqplay/releases/download/v0.8.1/jqplay_0.8.1_Darwin_x86_64"
      sha256 "a5ed79d57da6ed5bf04eb8d1dcc4fdafb90e16e607754eba80c54d291df42a05"

      def install
        bin.install "jqplay_0.8.1_Darwin_x86_64" => "jqplay"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jittering/jqplay/releases/download/v0.8.1/jqplay_0.8.1_Linux_x86_64"
      sha256 "5798f24a10e37f6c146eecd756eb6dcb1518defac8aa1b81b84e03579718aa78"

      def install
        bin.install "jqplay_0.8.1_Linux_x86_64" => "jqplay"
      end
    end
  end
end
