# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vproxy < Formula
  desc "zero-config virtual proxies with tls"
  homepage "https://github.com/jittering/vproxy"
  version "0.7"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/jittering/vproxy/releases/download/v0.7/vproxy_0.7_Darwin_x86_64.tar.gz"
    sha256 "aacaa76774a57bf7390d0e7183fa78785ffdf19bc009c10f98d4186f2530e474"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/jittering/vproxy/releases/download/v0.7/vproxy_0.7_Linux_x86_64.tar.gz"
    sha256 "6804a34a6c1deda637ca82581edcc1fedd122766b8417b924dd1b06a973cbd2e"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/jittering/vproxy/releases/download/v0.7/vproxy_0.7_Linux_arm64.tar.gz"
    sha256 "6e0022358f3068bbe982ba2eae178f35a411a2fc90de95f5b69577f6dcf3144b"
  end

  depends_on "mkcert"

  def install
    bin.install "vproxy"
  end

  def post_install
    str = <<-EOF
# Sample config file
# All commented settings below are defaults

# Enable verbose output
#verbose = false

[server]
# Enable verbose output (for daemon only)
#verbose = false

# IP on which server will listen
# To listen on all IPs, set listen = "0.0.0.0"
#listen = "127.0.0.1"

# Ports to listen on
#http = 80
#https = 443


# The following paths are set explicitly to facilitate running as root

# mkcert's CAROOT path
# Set to output of `mkcert -CAROOT`
caroot_path = "#{`mkcert -CAROOT`.strip}"

# Path where generated certificates should be stored
cert_path = "#{ENV['HOME']}/.vproxy"

# Path to mkcert program
mkcert_path = "#{`which mkcert`.strip}"

[client]
# Enable verbose output (for client only)
#verbose = false

#host = "127.0.0.1"
#http = 80

# Use this in local config files, i.e., a .vproxy.conf file located in a
# project folder
#bind = ""
EOF

# only create if it doesn't already exist
conf_file = "#{etc}/vproxy.conf"
if File.exist?(conf_file) then
  File.open(conf_file, "w") do |f|
    f.puts str.gsub(/^[\t ]+/, "")
  end
end

# always write new sample file
File.open(conf_file+".sample", "w") do |f|
  f.puts str.gsub(/^[\t ]+/, "")
end

  end

  plist_options :startup => false

  def plist; <<~EOS
    <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>KeepAlive</key>
    <dict>
      <key>SuccessfulExit</key>
      <false/>
    </dict>
    <key>Label</key>
    <string>#{plist_name}</string>
    <key>ProgramArguments</key>
    <array>
      <string>#{bin}/vproxy</string>
      <string>daemon</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>WorkingDirectory</key>
    <string>#{var}</string>
    <key>StandardErrorPath</key>
    <string>#{var}/log/vproxy.log</string>
    <key>StandardOutPath</key>
    <string>#{var}/log/vproxy.log</string>
  </dict>
</plist>

  EOS
  end

  test do
    system "#{bin}/vproxy --version"
  end
end
